// <auto-generated />
using Clicker_Back_.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Clicker_Back_.Migrations
{
    [DbContext(typeof(dbContext))]
    [Migration("20240411180417_Primeira")]
    partial class Primeira
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.21");

            modelBuilder.Entity("Clicker_Back_.Models.Batata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("qtdBatata")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Batatas");
                });

            modelBuilder.Entity("Clicker_Back_.Models.Upgrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("qtdColheitadeira")
                        .HasColumnType("INTEGER");

                    b.Property<int>("qtdFazendeiro")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Upgrades");
                });
#pragma warning restore 612, 618
        }
    }
}
